In [19]:
import numpy as np
from numpy import linalg as la
import matplotlib.pyplot as plt
import math

rng = np.random.default_rng(5)
m = 5
n = 3

A = rng.random(size=(m,n))
A1 = A
A = A*A

print('-----A----')
print(A)

U = np.eye(m)
U1 = np.eye(m)
V = np.eye(n)
V1 = np.eye(n)

f = np.zeros(n)
g = np.zeros(n)

u = np.zeros(m)
v = np.zeros(n)
u1 = np.zeros(m)

s1 = 0
s2 = 0
s3 = 0
s4 = 0
v1 = 0

m1 = 0
m2 = np.zeros(n)

for k in range (0,n-1):
    s1 = 0
    for j in range (k,m-1):
        s1 = s1 + A[j][k]*A[j][k]
    sigma = A[k][k]/la.norm(A[k][k])*math.sqrt(s1)
    u[k]=A[k][k] + sigma
    for i in range (k+1,m-1):
        u[i]=A[i][k]
    beta = u[k]*sigma
    A[k][k] = -sigma
    s2 = 0
    for j in range (k+1,n-1):
        for o in range (k,m-1):
            s2 = s2 + u[o]*A[o][j]
        tau = s2/beta
        for o in range (k,m-1):
            A[o][j] -= tau*u[o]
    tau = 0
    for i in range (0,m-1):
        for j in range (k,m-1):
            tau += U[i][j]*u[j]
        tau = tau/ beta
        for j in range (k,m-1):
            U[i][j] -= tau*u[j]
    if k < n-2 :
        s3 = 0
        for j in range (k+1, n-1):
            s3 += A[k][j]*A[k][j]
        s3 = math.sqrt(s3)
        sigma = A[k][k+1]/la.norm(A[k][k+1])*s3
        v[k+1] = A[k][k+1] + sigma
        for j in range (k+2, n-1):
            v[j] = A[k][j]
        gamma = v[k+1]*sigma
        A[k][k+1] = -sigma
        tau = 0
        s4 = 0
        for i in range (k+1,m-1):
            for j in range(k+1,n-1):
                s4 += A[i][j]*v[j]
            tau = s4/gamma
            for j in range(k+1,n-1):
                A[i][j] -= tau*v[j]
        tau = 0
        s4 = 0
        for i in range (1,n-1):
            for j in range(k+1,n-1):
                s4 = s4 + V[i][j]*v[j]
            tau = s4/gamma
            for j in range(k+1,n-1):
                V[i][j] -= tau*v[j]
    for i in range (0, n-1):
        f[i] = A[i][i]
        g[i] = A[i][i+1]
    f[n-1] = A[n-1][n-1]

[U1,A1,V1] = np.linalg.svd(A1)


print('-----AA----')
print(A)

for i in range (0,n-1):
    m2[i] = i
    for j in range(0,n-1):
        A[i][j] -= f[i]/g[i]*A[i+1][j]
for i in range (0, n-1):
    f[i] = A[i][i]
    for j in range(1, n-1):
        if f[i] > f[j]:
            m1 = f[i]
            f[i] = f[j]
            f[j] = m1            
    
print('-----------------')
print(f)


print('--------A1-------')
print(A1)

print('--------V-------')
print(V)

-----A----
[[0.64802971 0.65276832 0.26556043]
 [0.08168243 0.00290852 0.1469717 ]
 [0.16685036 0.00204984 0.00237731]
 [0.99835291 0.42558546 0.05499503]
 [0.18917937 0.94903874 0.80582509]]
-----AA----
[[-1.20464189  0.70433989  0.26556043]
 [ 0.08168243 -0.70248933  0.1469717 ]
 [ 0.16685036  0.23402044  0.00237731]
 [ 0.99835291  0.65991305  0.05499503]
 [ 0.18917937  0.94903874  0.80582509]]
-----------------
[-1.06493935  0.41607203  0.00237731]
--------A1-------
[2.19184608 0.70154301 0.30955356]
--------V-------
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
